# Generated by Django 5.0.1 on 2024-02-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windoid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('expire', models.DateField()),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
    ]
